Id: Adobe.flash-player-ppapi
Name: Adobe Flash Player PPAPI
Version: 32.0.0.371
Publisher: Adobe
Installers:
  - Arch: x64
    InstallerType: MSI
    Url: https://download.macromedia.com/pub/flashplayer/pdc/32.0.0.371/install_flash_player_32_ppapi.msi
    Sha256: 61e7f588ff47bcef253e46df6e4ff3d52d1beccd98199320769c4d07bda36437
